name: Release
on: 
  deployment
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: update deploy status
      uses: unacast/actions-github-deployment-status@0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: in_progress
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
           ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        maven-args: "-P sonatype"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@fleetpin.co.nz"
        
        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
        gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
        
        maven-repo-server-id: sonatype
        maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}
        
        access-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ashley-taylor/junit-report-annotations-action@master
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - name: update deploy status
      uses: unacast/actions-github-deployment-status@0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
      if: always()
